### ISSUE TITLE
'NAMES' crashes the server

### ISSUE THREAD

**Issue by Firestorck** [Fy-/domino#2]
Hello!
I am currently using domino to make my own IRC client, but during the implementation of the "NAMES" command, I have seen that the server crashes any time that command is used.

The server doesn't actually stop, but doesn't respond to anything past that point, and i have an error message comming from it.

```
Traceback (most recent call last):

  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run

  File "/home/mael/.local/lib/python3.9/site-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)

  File "/home/mael/OneDrive/PythonIRC/server/domino/domino/server.py", line 95, in handle
    IRCProtocol.parse(line, user)

  File "/home/mael/OneDrive/PythonIRC/server/domino/domino/parser.py", line 58, in parse
    IRCProtocol.handle_cmd(user, command, args)

  File "/home/mael/OneDrive/PythonIRC/server/domino/domino/parser.py", line 29, in handle_cmd
    getattr(handle, command)(user, args)

  File "/home/mael/OneDrive/PythonIRC/server/domino/domino/handle/chan.py", line 61, in NAMES
    send_numeric(461, [user.nick, 'NAMES'], ':Not enough parameters')

TypeError: send_numeric() missing 1 required positional argument: 'user'
2021-09-17T14:11:15Z <Greenlet at 0x7fda99a93370: _handle_and_close_when_done(<bound method Domino.handle of <domino.server.Domi, <bound method StreamServer.do_close of <StreamServ, (<gevent._socket3.socket [closed] at 0x7fda99592ac)> failed with TypeError
```

Edit : added spacing in the error & fixing the code block

**Comment by Fy-** [comment]
Hey nice to see someone is using this project lol, I made this just for fun. I'll check your bug tomorrow :)

**Comment by Firestorck** [comment]
Nice thanks! Apparently, it seems to also occur when using "MODE #domino +b" with the error 
```
<<< MODE #domino +b

Traceback (most recent call last):

  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run

  File "/home/mael/.local/lib/python3.9/site-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)

  File "/home/mael/OneDrive/PythonIRC/server/domino/domino/server.py", line 95, in handle
    IRCProtocol.parse(line, user)

  File "/home/mael/OneDrive/PythonIRC/server/domino/domino/parser.py", line 58, in parse
    IRCProtocol.handle_cmd(user, command, args)

  File "/home/mael/OneDrive/PythonIRC/server/domino/domino/parser.py", line 29, in handle_cmd
    getattr(handle, command)(user, args)

  File "/home/mael/OneDrive/PythonIRC/server/domino/domino/handle/user.py", line 99, in MODE
    chan.modes.send()

TypeError: send() missing 1 required positional argument: 'user'

2021-09-20T15:19:16Z <Greenlet at 0x7fb4d1d12480: _handle_and_close_when_done(<bound method Domino.handle of <domino.server.Domi, <bound method StreamServer.do_close of <StreamServ, (<gevent._socket3.socket [closed] at 0x7fb4d17e6e8)> failed with TypeError
```

Edit : spacing & code block
