### ISSUE TITLE
Couldn't install old greenlet and gevent, and the code seems to be incompatible with the new gevent

### ISSUE THREAD

**Issue by inhahe** [Fy-/domino#5]
I got the following errors when running `pip install -r requirements.txt`:

```
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [47 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'greenlet' extension
      creating build
      creating build\temp.win-amd64-cpython-311
      creating build\temp.win-amd64-cpython-311\Release
      "C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.35.32213\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\inhah\Envs\domino2\include -IC:\Python311\include -IC:\Python311\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.35.32213\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.35.32213\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /Tcgreenlet.c /Fobuild\temp.win-amd64-cpython-311\Release\greenlet.obj
      greenlet.c
      greenlet.c(160): error C2039: 'exc_type': is not a member of '_err_stackitem'
      C:\Python311\include\cpython/pystate.h(55): note: see declaration of '_err_stackitem'
      greenlet.c(162): error C2039: 'exc_traceback': is not a member of '_err_stackitem'
      C:\Python311\include\cpython/pystate.h(55): note: see declaration of '_err_stackitem'
      greenlet.c(476): error C2039: 'recursion_depth': is not a member of '_ts'
      C:\Python311\include\cpython/pystate.h(82): note: see declaration of '_ts'
      greenlet.c(477): error C2039: 'frame': is not a member of '_ts'
      C:\Python311\include\cpython/pystate.h(82): note: see declaration of '_ts'
      greenlet.c(506): error C2039: 'recursion_depth': is not a member of '_ts'
      C:\Python311\include\cpython/pystate.h(82): note: see declaration of '_ts'
      greenlet.c(507): error C2039: 'frame': is not a member of '_ts'
      C:\Python311\include\cpython/pystate.h(82): note: see declaration of '_ts'
      greenlet.c(538): error C2039: 'use_tracing': is not a member of '_ts'
      C:\Python311\include\cpython/pystate.h(82): note: see declaration of '_ts'
      greenlet.c(541): error C2039: 'use_tracing': is not a member of '_ts'
      C:\Python311\include\cpython/pystate.h(82): note: see declaration of '_ts'
      greenlet.c(771): error C2039: 'recursion_depth': is not a member of '_ts'
      C:\Python311\include\cpython/pystate.h(82): note: see declaration of '_ts'
      greenlet.c(823): warning C4996: 'PyEval_CallObjectWithKeywords': deprecated in 3.9
      greenlet.c(952): error C2039: 'exc_type': is not a member of '_err_stackitem'
      C:\Python311\include\cpython/pystate.h(55): note: see declaration of '_err_stackitem'
      greenlet.c(952): error C2198: 'visit': too few arguments for call
      greenlet.c(954): error C2039: 'exc_traceback': is not a member of '_err_stackitem'
      C:\Python311\include\cpython/pystate.h(55): note: see declaration of '_err_stackitem'
      greenlet.c(954): error C2198: 'visit': too few arguments for call
      greenlet.c(984): error C2039: 'exc_type': is not a member of '_err_stackitem'
      C:\Python311\include\cpython/pystate.h(55): note: see declaration of '_err_stackitem'
      greenlet.c(986): error C2039: 'exc_traceback': is not a member of '_err_stackitem'
      C:\Python311\include\cpython/pystate.h(55): note: see declaration of '_err_stackitem'
      greenlet.c(1009): error C2106: '=': left operand must be l-value
      greenlet.c(1038): error C2105: '--' needs l-value
      greenlet.c(1042): error C2106: '=': left operand must be l-value
      greenlet.c(1046): error C2065: '_Py_DEC_REFTOTAL': undeclared identifier
      greenlet.c(1059): error C2039: 'exc_type': is not a member of '_err_stackitem'
      C:\Python311\include\cpython/pystate.h(55): note: see declaration of '_err_stackitem'
      greenlet.c(1061): error C2039: 'exc_traceback': is not a member of '_err_stackitem'
      C:\Python311\include\cpython/pystate.h(55): note: see declaration of '_err_stackitem'
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Preview\\VC\\Tools\\MSVC\\14.35.32213\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for greenlet
```

And it didn't install gevent either, so I install greenlet and gevent using https://files.pythonhosted.org/packages/7e/a6/0a34cde83fe520fa4e8192a1bc0fc7bf9f755215fefe3f42c9b97c45c620/greenlet-2.0.2-cp311-cp311-win_amd64.whl and 
https://files.pythonhosted.org/packages/26/5d/f5d1ad8e64ea16543131f4b7c189b675f73f6dc8e9fb6546c6e6421f43a7/gevent-22.10.2-cp311-cp311-win_amd64.whl. Werkzeug and sqlalchemy weren't installed either, so I installed them without bothering with the version limitations. Then I ran `python run.py` and got the following error:

```
[Domino] Welcome to domino-ircd
[Domino] [Deadpool] Loading Deadpool
[<deadpool.chanserv.DeadpoolChan object at 0x000002A11A403250>, <deadpool.chanserv.DeadpoolChan object at 0x000002A11A4032D0>]
[Domino] [Deadpool] I will shoot your f*cking cat! - Loaded
[Domino] [ServerSideSmiley] Loading ServerSideSmiley
[Domino] [ServerSideSmiley] ❤‿❤ - Loaded
[Domino] Starting domino on 0.0.0.0:6667 ...
Traceback (most recent call last):
  File "D:\domino-master\run.py", line 38, in <module>
    main()
  File "D:\domino-master\run.py", line 35, in main
    srv.run() #: Run
    ^^^^^^^^^
  File "D:\domino-master\domino\server.py", line 108, in run
    self.server.serve_forever()
  File "C:\Users\inhah\Envs\domino2\Lib\site-packages\gevent\baseserver.py", line 398, in serve_forever
    self.start()
  File "C:\Users\inhah\Envs\domino2\Lib\site-packages\gevent\baseserver.py", line 336, in start
    self.init_socket()
  File "C:\Users\inhah\Envs\domino2\Lib\site-packages\gevent\server.py", line 180, in init_socket
    self.socket = self.get_listener(self.address, self.backlog, self.family)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\inhah\Envs\domino2\Lib\site-packages\gevent\server.py", line 192, in get_listener
    return _tcp_listener(address, backlog=backlog, reuse_addr=cls.reuse_addr, family=family)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\inhah\Envs\domino2\Lib\site-packages\gevent\server.py", line 288, in _tcp_listener
    sock.bind(address)
  File "C:\Users\inhah\Envs\domino2\Lib\site-packages\gevent\_socketcommon.py", line 563, in bind
    return self._sock.bind(address)
           ^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted: ('0.0.0.0', 6667)
                - update_all - check pings and timeouts...
```

**Comment by inhahe** [comment]
ps. does domino support SASL?
